# -*- coding: utf-8 -*-

from typing import Any, Dict

from docutils.core import publish_parts
import m2r

from wdom import options, server
from wdom.document import get_document, set_app
from wdom.event import Event
from wdom.parser import parse_html

if options.config.theme is None:
    options.config.theme = 'skyblue'  # Fake command line option
from wdom.themes import default, RawHtmlNode  # noqa: E402
from wdom.themes.default import Col6, Col12, Div, Row, Textarea  # noqa: E402
from wdom.themes.default import H1, Hr, Pre  # noqa: E402
from wdom.themes.default import Select, Option  # noqa: E402

converter = m2r.M2R()
src = '''
# M2R Preview

This is a m2r demo editor.

You can **directly** write `Markdown`, :code:`reStructuredText`, and
<span style="color: #b33;">Raw HTML</span>.

## Source Code Example

Markdown style:

```py
print('Hello, M2R!')
```

### reStructuredText Directives

.. code:: python

   print('Hello, WDOM!')

.. note::

   reST directives are also OK!

'''


def parse2rst(text: str) -> str:
    rst = converter(text)
    return rst


def parse(text: str) -> Dict[str, str]:
    rst = parse2rst(text)
    output = publish_parts(source=rst, writer_name='html5')
    return output


class Selector(Select):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.opt1 = Option(parent=self, value='html')
        self.opt1.textContent = 'HTML'
        self.opt2 = Option(parent=self, value='raw_html')
        self.opt2.textContent = 'Raw HTML'
        self.opt3 = Option(parent=self, value='rst')
        self.opt3.textContent = 'reST'


class App(Row):
    def __init__(self) -> None:
        super().__init__()
        self.doc = get_document()
        self.style = 'height: 80vh;'
        editor_col = Col6(parent=self)
        self.editor = Textarea(parent=editor_col)
        self.editor.style = 'font-family: monospace; height: 80vh; width: 95%;'
        self.editor.addEventListener('input', self.preview)
        self.editor.textContent = src  # set initial text

        viewer_col = Col6(parent=self)

        self.selector_row = Row(parent=viewer_col, style='text-align: center;')
        self.selector_row.append('Output Format: ')
        self.selector = Selector(parent=self.selector_row,
                                 style='width: auto; display: inline;')
        self.selector.addEventListener('change', self.preview)

        self.viewer_row = Row(parent=viewer_col)
        self.viewer = Col12(parent=self.viewer_row)
        self.viewer.style = '''
            height: 100%;
            margin-top: 1rem;
            padding: 1rem 2rem;
            border: 1px solid #ddd;
            border-radius: 3px;
        '''

        # set stylesheets generated by docutils
        output = parse(src)
        _style = parse_html(output['stylesheet'])
        self.doc.head.appendChild(_style)
        self.viewer.appendChild(RawHtmlNode(output['html_body']))

    def update(self, text: str) -> None:
        if self.selector.value == self.selector.opt3.value:
            self.viewer.replaceChild(Pre(parse2rst(text)),
                                     self.viewer.firstChild)
        else:
            html = parse(text)['html_body']
            if self.selector.value == self.selector.opt2.value:
                self.viewer.replaceChild(Pre(html), self.viewer.firstChild)
            else:
                self.viewer.replaceChild(RawHtmlNode(html),
                                         self.viewer.firstChild)

    def preview(self, event: Event) -> None:
        content = self.editor.textContent
        self.update(content)


def sample_page() -> Div:
    doc = get_document()
    doc.register_theme(default)
    doc.title = 'M2R DEMO'
    app = Div(style='width: 90vw; margin: auto;')
    title = H1('M2R DEMO Editor', style='text-align: center;')
    subtitle = Div('Powered by WDOM',
                   style='text-align: right; margin-top: 1rem;')
    app.append(title, Hr(), App(), subtitle)
    return app


def main() -> None:
    set_app(sample_page())
    server.start()
